SELECT * FROM CAR;

--1. BASIC DATASET OVERVIEW

-- Total records
SELECT COUNT(*) AS total_records FROM CAR;

-- Check duplicate records (based on CAR_ID)
SELECT CAR_ID, COUNT(*) AS duplicate_count
FROM CAR
GROUP BY CAR_ID
HAVING COUNT(*) > 1;

-- Check missing values in each column
SELECT
SUM(CASE WHEN BRAND IS NULL THEN 1 ELSE 0 END) AS missing_brand,
SUM(CASE WHEN YEAR IS NULL THEN 1 ELSE 0 END) AS missing_year,
SUM(CASE WHEN ENGINE_SIZE IS NULL THEN 1 ELSE 0 END) AS missing_engine_size,
SUM(CASE WHEN FUEL_TYPE IS NULL THEN 1 ELSE 0 END) AS missing_fuel_type,
SUM(CASE WHEN TRANSMISSION IS NULL THEN 1 ELSE 0 END) AS missing_transmission,
SUM(CASE WHEN MILEAGE IS NULL THEN 1 ELSE 0 END) AS missing_mileage,
SUM(CASE WHEN CONDITION IS NULL THEN 1 ELSE 0 END) AS missing_condition,
SUM(CASE WHEN PRICE IS NULL THEN 1 ELSE 0 END) AS missing_price
FROM CAR;




 --   2. DESCRIPTIVE STATISTICS


-- Price statistics
SELECT 
MIN(PRICE) AS min_price,
MAX(PRICE) AS max_price,
ROUND(AVG(PRICE),2) AS avg_price
FROM CAR;

-- Mileage statistics
SELECT 
MIN(MILEAGE) AS min_mileage,
MAX(MILEAGE) AS max_mileage,
ROUND(AVG(MILEAGE),2) AS avg_mileage
FROM CAR;

-- Average price per brand
SELECT BRAND, COUNT(*) AS total_cars,
ROUND(AVG(PRICE),2) AS avg_price,
MIN(PRICE) AS min_price,
MAX(PRICE) AS max_price
FROM CAR
GROUP BY BRAND
ORDER BY avg_price DESC;



--    3. CATEGORY-WISE ANALYSIS

-- Cars by fuel type
SELECT FUEL_TYPE, COUNT(*) AS total_cars,
ROUND(AVG(PRICE),2) AS avg_price
FROM CAR
GROUP BY FUEL_TYPE;

-- Cars by transmission type
SELECT TRANSMISSION, COUNT(*) AS total_cars,
ROUND(AVG(PRICE),2) AS avg_price
FROM CAR
GROUP BY TRANSMISSION;

-- Cars by condition
SELECT CONDITION, COUNT(*) AS total_cars,
ROUND(AVG(PRICE),2) AS avg_price
FROM CAR
GROUP BY CONDITION
ORDER BY avg_price DESC;



--    4. TREND ANALYSIS


-- Car age impact on price
SELECT (2025 - YEAR) AS CAR_AGE,
ROUND(AVG(PRICE),2) AS avg_price,
COUNT(*) AS total_cars
FROM CAR
GROUP BY (2025 - YEAR)
ORDER BY CAR_AGE;

-- Engine size vs price
SELECT ENGINE_SIZE,
ROUND(AVG(PRICE),2) AS avg_price,
COUNT(*) AS total_cars
FROM CAR
GROUP BY ENGINE_SIZE
ORDER BY ENGINE_SIZE;



--    5. BEST & WORST PERFORMING CARS

-- Top 5 highest priced cars
SELECT * FROM (
SELECT BRAND, MODEL, PRICE, MILEAGE, YEAR
FROM CAR
ORDER BY PRICE DESC
) WHERE ROWNUM <= 5;

-- Top 5 highest mileage cars
SELECT * FROM (
SELECT BRAND, MODEL, PRICE, MILEAGE
FROM CAR
ORDER BY MILEAGE DESC
) WHERE ROWNUM <= 5;



--    6. OUTLIER DETECTION

-- Price outliers using Mean ± 2*StdDev
SELECT CAR_ID, BRAND, MODEL, PRICE
FROM CAR
WHERE PRICE > (SELECT AVG(PRICE) + 2 * STDDEV(PRICE) FROM CAR)
OR PRICE < (SELECT AVG(PRICE) - 2 * STDDEV(PRICE) FROM CAR);

-- Mileage outliers using Mean ± 2*StdDev
SELECT CAR_ID, BRAND, MODEL, MILEAGE
FROM CAR
WHERE MILEAGE > (SELECT AVG(MILEAGE) + 2 * STDDEV(MILEAGE) FROM CAR)
OR MILEAGE < (SELECT AVG(MILEAGE) - 2 * STDDEV(MILEAGE) FROM CAR);


--7. MILEAGE VS PRICE CATEGORY ANALYSIS

SELECT
CASE 
WHEN MILEAGE < 50000 THEN 'Low Mileage'
WHEN MILEAGE BETWEEN 50000 AND 150000 THEN 'Medium Mileage'
ELSE 'High Mileage'
END AS mileage_category,
ROUND(AVG(PRICE),2) AS avg_price,
COUNT(*) AS total_cars
FROM CAR
GROUP BY 
CASE 
WHEN MILEAGE < 50000 THEN 'Low Mileage'
WHEN MILEAGE BETWEEN 50000 AND 150000 THEN 'Medium Mileage'
ELSE 'High Mileage'
END;


-- 8. CREATE VIEW FOR FUTURE ANALYSIS


CREATE OR REPLACE VIEW V_CAR_EDA AS
SELECT CAR_ID, BRAND, MODEL, YEAR, ENGINE_SIZE, FUEL_TYPE, 
TRANSMISSION, MILEAGE, CONDITION, PRICE,
(2025 - YEAR) AS CAR_AGE
FROM CAR;

-- View result
SELECT * FROM V_CAR_EDA;
